spring:
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd

wx:
  appid: wx91d81d9fda4fb784
  appsecret: 4dff4b4cc2879ca5b1d60eda34617848
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
missyou:
  security:
    jwt-key: mrguo
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host:
    pay-callback-path: /v1/payment/wx/notify
  year-codes: A,B,C,D,E,F,G,H,J,K
